// NOTES //
export const CHANGE_CURRENT_KEY = 'CHANGE_CURRENT_KEY';
export const CHANGE_CURRENT_TYPE = 'CHANGE_CURRENT_TYPE';
export const CHANGE_CURRENT_SUBTYPE = 'CHANGE_CURRENT_SUBTYPE';
export const CHANGE_CURRENT_NOTE_PLAYING = 'CHANGE_CURRENT_NOTE_PLAYING';
export const START_PLAYBACK = 'START_PLAYBACK';
export const STOP_PLAYBACK = 'STOP_PLAYBACK';

// SETTINGS //
export const CHANGE_NO_OCTAVES = 'CHANGE_NO_OCTAVES';

// Fetch user settings
export const FETCH_USER_SETTINGS_START = 'FETCH_USER_SETTINGS_START';
export const FETCH_USER_SETTINGS_SUCCESS = 'FETCH_USER_SETTINGS_SUCCESS';
export const FETCH_USER_SETTINGS_FAIL = 'FETCH_USER_SETTINGS_FAIL';
// Save user settings
export const SAVE_USER_SETTINGS_START = 'SAVE_USER_SETTINGS_START';
export const SAVE_USER_SETTINGS_SUCCESS = 'SAVE_USER_SETTINGS_SUCCESS';
export const SAVE_USER_SETTINGS_FAIL = 'SAVE_USER_SETTINGS_FAIL';

// FAVOURITES //
export const SAVE_FAVOURITE = 'SAVE_FAVOURITE';
export const SORT_FAVOURITES = 'SORT_FAVOURITES';
export const DELETE_FAVOURITE = 'DELETE_FAVOURITE';
export const SELECT_FAVOURITE = 'SELECT_FAVOURITE';

// AUTHORISATION //
export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';

// SWITCH AUTHORISATION MODE //
export const SWITCH_AUTH_MODE = 'SWITCH_AUTH_MODE';

// LOGOUT //
export const LOGOUT_START = 'LOGOUT';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';

// ADD USERS //
export const ADD_USER_START = 'ADD_USER_START';
export const ADD_USER_SUCCESS = 'ADD_USER_SUCCESS';
export const ADD_USER_FAIL = 'ADD_USER_FAIL';

// DELETE USER //
export const DELETE_USER_START = 'DELETE_USER_START';
export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS';

// GET USER DETAILS //
export const GET_USER_DETAILS = 'GET_USER_DETAILS';
export const GET_USER_DETAILS_START = 'GET_USER_DETAILS_START';
export const GET_USER_DETAILS_SUCCESS = 'GET_USER_DETAILS_SUCCESS';
export const GET_USER_DETAILS_FAIL = 'GET_USER_DETAILS_FAIL';

// MODAL //
export const SHOW_MODAL = 'SHOW_MODAL';
export const HIDE_MODAL = 'HIDE_MODAL';
export const SET_MODAL_CONTENT = 'SET_MODAL_CONTENT';

// POPUP //
export const SHOW_POPUP = 'SHOW_POPUP';
export const HIDE_POPUP = 'HIDE_POPUP';
export const SET_POPUP_CONTENT = 'SET_POPUP_CONTENT';